# Website info
title: Another Theme
email: hey@miltonolaf.com
twitter: olafmilton
github: miltonolaf
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miltonolaf.com/another" # the base hostname & protocol for your site, e.g. http://example.com

# Theme Settings
another:
  custom_menu: false
  deactivate_dark_mode: true
  analytics_id: false
  disqus_id: false


favicon: favicon.png # favicon name in assets/img/

permalink: /:year/:month/:title/

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  profile: false
  blanklines: true
  startings: [html, head, body]

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
