# Website info
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miltonolaf.com/another" # the base hostname & protocol for your site, e.g. http://example.com

# Theme Settings
author:
  twitter: olafmilton
  name: Milton Olaf Paredes

favicon: favicon.png # favicon name in assets/img/

permalink: /:year/:month/:title/

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  profile: false
  blanklines: true
  startings: [html, head, body]

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-github-metadata

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
